openapi: "3.0.0"
info:
  title: "Node Bootstrap API"
  version: "1.0.0"
  description: "API for managing authentication and user operations"
tags:
  - name: "user"
    description: "Endpoints for user management"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
